# -*- coding: utf-8 -*-
"""vendas-ltsm-walmart.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11MuU1BuhZRGK9B5OoWE3QkBCcMAMZdnZ
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics import mean_squared_error

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, LSTM, Dropout, InputLayer
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.callbacks import EarlyStopping

from google.colab import files
uploaded = files.upload()

df = pd.read_csv('Walmart_Sales.csv')

df['Date'] = pd.to_datetime(df['Date'], dayfirst=True)

# NÃO agregar!
df = df.sort_values(['Store', 'Date'])

# Log apenas na venda
df['Weekly_Sales'] = np.log1p(df['Weekly_Sales'])

df.head()

features = df[['Weekly_Sales', 'Holiday_Flag', 'Temperature',
               'Fuel_Price', 'CPI', 'Unemployment']]

dados = features.values

def criar_dataset(conjunto, passo=52):
    X, y = [], []
    for i in range(len(conjunto) - passo):
        X.append(conjunto[i:i+passo])
        y.append(conjunto[i+passo, 0])  # predição vendas
    return np.array(X), np.array(y)

passo = 52

X, y = criar_dataset(dados, passo)

print(X.shape, y.shape)

tamanho_treino = int(len(X) * 0.8)

X_treino, X_teste = X[:tamanho_treino], X[tamanho_treino:]
y_treino, y_teste = y[:tamanho_treino], y[tamanho_treino:]

scaler = MinMaxScaler()

# Fit só no treino
scaler.fit(X_treino.reshape(-1, X.shape[2]))

# Transformar
X_treino = scaler.transform(X_treino.reshape(-1, X.shape[2])).reshape(X_treino.shape)
X_teste = scaler.transform(X_teste.reshape(-1, X.shape[2])).reshape(X_teste.shape)

limite = np.percentile(y_treino, 90)
pesos = np.where(y_treino > limite, 2.0, 1.0)

modelo = Sequential([
    InputLayer(input_shape=(passo, X.shape[2])),

    LSTM(128, return_sequences=True),
    Dropout(0.3),

    LSTM(128, return_sequences=True),
    Dropout(0.3),

    LSTM(64),

    Dense(64, activation='relu'),
    Dense(1)
])

modelo.compile(
    optimizer=Adam(learning_rate=0.001),
    loss='mae'
)

modelo.summary()

early_stop = EarlyStopping(
    monitor='val_loss',
    patience=15,
    restore_best_weights=True
)

historico = modelo.fit(
    X_treino, y_treino,
    epochs=150,
    batch_size=32,
    validation_data=(X_teste, y_teste),
    sample_weight=pesos,
    callbacks=[early_stop],
    verbose=1
)

pred = modelo.predict(X_teste)

# inverte o log
pred_final = np.expm1(pred)
y_real_final = np.expm1(y_teste.reshape(-1,1))

plt.figure(figsize=(15,6))

plt.plot(y_real_final, label="Real", marker='o', alpha=0.6)
plt.plot(pred_final, label="Previsto", linewidth=2)

plt.title("Previsão de Vendas Walmart (LSTM)")
plt.ylabel("Vendas ($)")
plt.legend()
plt.grid(True)

plt.show()

mae = np.mean(np.abs(pred_final - y_real_final))
rmse = np.sqrt(mean_squared_error(y_real_final, pred_final))

print(f"MAE: $ {mae:,.2f}")
print(f"RMSE: $ {rmse:,.2f}")